# Generated by Django 2.2.1 on 2019-06-17 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=120)),
                ('nickname', models.CharField(max_length=120)),
                ('profile_photo', models.URLField()),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('post_body', models.TextField(default='text')),
                ('hate_user', models.ManyToManyField(related_name='hate_post', to='api.User')),
                ('like_user', models.ManyToManyField(related_name='like_post', to='api.User')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='comment')),
                ('hate_user', models.ManyToManyField(related_name='hate_comment', to='api.User')),
                ('like_user', models.ManyToManyField(related_name='like_comment', to='api.User')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Post')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.User')),
            ],
        ),
    ]
